[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14


# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
# background = '#282828'
# soft contrast background = = '#32302f'
# foreground = '#ebdbb2'

# # My Colors
background = "#000000"
foreground = "#00ff00"

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
white   = '#a89984'

magenta = '#ff00ff'
cyan    = '#00ffff'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
white   = '#ebdbb2'

magenta = '#ff00ff'
cyan    = '#00ffff'




# # Colors (High Contrast)
#
# # Default colors
# [colors.primary]
# # Theme default
# # background = '#444444'
# # foreground = '#dddddd'
#
# # My Colors
# background = "#000000"
# foreground = "#00ff00"
#
# # Colors the cursor will use if `custom_cursor_colors` is true
# [colors.cursor]
# text = '#aaaaaa'
# cursor = '#ffffff'
#
# # Normal colors
# [colors.normal]
# black   = '#000000'
# red     = '#ff0000'
# green   = '#00ff00'
# yellow  = '#ffff00'
# blue    = '#0000ff'
# magenta = '#ff00ff'
# cyan    = '#00ffff'
# white   = '#ffffff'
#
# # Bright colors
# [colors.bright]
# black   = '#000000'
# red     = '#ff0000'
# green   = '#00ff00'
# yellow  = '#ffff00'
# blue    = '#0000ff'
# magenta = '#ff00ff'
# cyan    = '#00ffff'
# white   = '#ffffff'

# COLORS RANDOM PEOPLE
# [colors.cursor]
# text = "#282828"
# cursor = "#ebdbb2"
#
# [colors.normal]
# black   = "#282828"
# red     = "#cc241d"
# green   = "#98971a"
# yellow  = "#d79921"
# blue    = "#458588"
# magenta = "#b16286"
# cyan    = "#689d6a"
# white   = "#a89984"
#
# [colors.bright]
# black   = "#928374"
# red     = "#fb4934"
# green   = "#b8bb26"
# yellow  = "#fabd2f"
# blue    = "#83a598"
# magenta = "#d3869b"
# cyan    = "#8ec07c"
# white   = "#ebdbb2"

